spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/note_sharing_db
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
